### ISSUE TITLE
 Caught exception from si.core

### ISSUE THREAD

**Issue by t3mainframe** [jeffpengMC/SI-Mods#12]
Ver 1.4.1.1

[23:27:48] [Server thread/ERROR] [FML]: Caught exception from si.core
java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
        at com.jeffpeng.si.core.registry.SIRegistry.getCreativeTabByName(SIRegistry.java:98) ~[SIRegistry.class:?]
        at com.jeffpeng.si.core.registry.SIBlockRegistry.instantiateAndListBlock(SIBlockRegistry.java:44) ~[SIBlockRegistry.class:?]
        at com.jeffpeng.si.core.registry.SIBlockRegistry.instantiateAndListBlocks(SIBlockRegistry.java:75) ~[SIBlockRegistry.class:?]
        at com.jeffpeng.si.core.registry.SIRegistry.registerContentToGame(SIRegistry.java:59) ~[SIRegistry.class:?]
        at com.jeffpeng.si.core.SI.preInit(SI.java:57) ~[SI.class:?]

**Comment by t3mainframe** [comment]
Looks like ver 1.4.1.5 fixes this problem good job :)
